---
version: '3'
services:


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    hostname: elasticsearch
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      - 'xpack.monitoring.collection.enabled=true'
    ports:
      - '127.0.0.1:9200:9200'
    networks:
      - stack


  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}
    hostname: kibana
    ports:
      - '127.0.0.1:5601:5601'
    networks:
      - stack
    depends_on:
      - elasticsearch


  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_STACK_VERSION}
    hostname: logstash
    environment:
      - 'xpack.monitoring.enabled=true'
    ports:
      - '127.0.0.1:4560:4560'
      - '127.0.0.1:5044:5044'
    volumes:
      # Provide a pipeline configuration for Logstash with a bind-mounted file
      - ./docker-compose/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - stack
    depends_on:
      - elasticsearch


  # Filebeat sending data to Logstash
  filebeat_for_logstash:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    hostname: filebeat_for_logstash
    volumes:
      # Bind-mount the logs/ directory, so Filebeat can read its files
      - './logs/:/mnt/logs/:ro'
      # Bind-mount a custom configuration file
      - './docker-compose/filebeat-logstash.yml:/usr/share/filebeat/filebeat.yml:ro'
      # Bind-mount the prospectors directory, so configurations can be dynamically loaded
      - './docker-compose/filebeat-logstash/prospectors.d/:/usr/share/filebeat/prospectors.d/:ro'
      # Bind-mount the registry file to avoid data duplication between restarts
      - './docker-compose/filebeat-logstash/registry/:/usr/share/filebeat/data/'
    command: filebeat -e
    restart: on-failure
    networks:
      - stack
    depends_on:
      - elasticsearch
      - logstash


  # Filebeat sending data to Elasticsearch
  filebeat_for_elasticsearch:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    hostname: filebeat_for_elasticsearch
    volumes:
      # Bind-mount the logs/ directory, so Filebeat can read its files
      - './logs/:/mnt/logs/:ro'
      # Bind-mount a custom configuration file
      - './docker-compose/filebeat-elasticsearch.yml:/usr/share/filebeat/filebeat.yml:ro'
      # Bind-mount the prospectors directory, so configurations can be dynamically loaded
      - './docker-compose/filebeat-elasticsearch/prospectors.d/:/usr/share/filebeat/prospectors.d/:ro'
      # Bind-mount the registry file to avoid data duplication between restarts
      - './docker-compose/filebeat-elasticsearch/registry/:/usr/share/filebeat/data/'
    command: 'filebeat -e'
    restart: on-failure
    networks:
      - stack
    depends_on:
      - elasticsearch
      - kibana


  #Short lived container to configure the stack once Kibana and Elasticsearch are available
  configure_stack:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    hostname: configure_stack
    volumes:
      - './docker-compose/setup.sh:/usr/local/bin/setup.sh:ro'
    command: '/usr/local/bin/setup.sh'
    networks:
      - stack
    depends_on:
      - elasticsearch
      - kibana


networks:
  stack: {}
